### ISSUE TITLE
Ошибка в выставлении адреса ноды

### ISSUE THREAD

**Issue by Difrex** [idec-net/idec.el#1]
От сюда: https://github.com/Difrex/idec.el/issues/1

В разделе customize-group -> idec пытаюсь всё настроить
Когда дохожу до idec-primary-node и пробую применить, то Емакс выдаёт вот это

Symbol's value as variable is void: http://idec\.spline-online\.tk/

И изменения не сохраняет

**Comment by vit1-irk** [comment]
Кстати, у тебя на скриншоте эта настройка записана словами

Idec Primary Node:

А у меня она выглядит как idec-primary-node

**Comment by Difrex** [comment]
Укажи там урл в кавычках - работает. Чистый конфиг с которым пробовал:
```lisp
(require 'package)

(defun configure-repos ()
    "Set MELPA and ELPA repositories."
    (require 'package)
    (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                        (not (gnutls-available-p))))
           (proto (if no-ssl "http" "https")))
        ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
        (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
        ;; (add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
        (when (< emacs-major-version 24)
            ;; For important compatibility libraries like cl-lib
            (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
    (package-initialize))

(configure-repos)

(package-install 'emacsql-sqlite)
(package-install 'web)
(package-install 'dash)

;; IDEC
(add-to-list 'load-path "~/projects/idecel")
(require 'idec-mode)
```

Моя версия Emacs: `This is GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2018-05-29`

**Comment by vit1-irk** [comment]
С кавычками работает. Но это, очевидно, баг, потому что всё остальное сохраняется без кавычек

**Comment by Difrex** [comment]
Да, я согласен, что это баг, по-этому и не закрываю таск
