### ISSUE TITLE
idec-load-new-messages fail

### ISSUE THREAD

**Issue by vit1-irk** [idec-net/idec.el#2]
Symbol's function definition is void: f-file\?

**Comment by vit1-irk** [comment]
Перед знаком вопроса ещё бэкслеш

**Comment by Difrex** [comment]
Да, я уже воспроизвел у себя. Теперь нужно понять почему так происходит =)

**Comment by Difrex** [comment]
Добавил в README зависимость. Поставь себе https://github.com/rejeep/f.el

**Comment by Difrex** [comment]
@vit1-irk  помогло?

**Comment by vit1-irk** [comment]
Спасибо, работает

**Comment by vit1-irk** [comment]
Правда, пользоваться клиентом всё равно трудно

Потому что сообщения не в хронологическом порядке
Я пока не в курсе, проблема ноды это или клиента

**Comment by Difrex** [comment]
После M-x idec-load-new-messages показываются сообщения в хронологическом порядке по эхе.
Забираю сообщния с idec.spline-online.tk

![2018-06-26 10-27-49](https://user-images.githubusercontent.com/3982213/41895790-a13337e2-792b-11e8-89eb-93aad5d54314.png)

**Comment by vit1-irk** [comment]
Проверил только что, проблема на моей ноде, видимо
