### ISSUE TITLE
Переносы строки ^M в некоторых сообщениях

### ISSUE THREAD

**Issue by vit1-irk** [idec-net/idec.el#3]
Как убрать сабж, чтобы можно было нормально читать?

// Похоже на проделки виндузятников

**Comment by Difrex** [comment]
Да, знаю про проблему, пока хз как с этим бороться.

**Comment by vit1-irk** [comment]
Просто удалять из текста, разве нет?

**Comment by Difrex** [comment]
> Просто удалять из текста, разве нет?

Ага, только вот так вот почему-то не работает:
```lisp
(replace-in-string "^M" "" (s-join "\n" (get-message-field (gethash "content" msg-hash) "body")))))
```

**Comment by vit1-irk** [comment]
А разве не "\r" ?

**Comment by Difrex** [comment]
> А разве не "\r" ?

Так тоже не работает =)
